novasamatech/nova-wallet-ios-releases

- updates/changelogs/release/5_3_0.md
- updates/v1/entrypoint_release.json
Reverts nova-wallet/nova-wallet-ios-releases#1
> Revert "Add release for Appstore link test"

- updates/changelogs/release/5_4_0.md
- updates/v1/entrypoint_release.json
> Add release notes for 5_4_0 Critical update

- updates/changelogs/release/5_4_0.md
- updates/changelogs/release/6_0_0.md
- updates/v1/entrypoint_release.json
> Add release notes for 6_0_0 Major update

- updates/changelogs/release/6_1_2.md
- updates/v1/entrypoint_release.json
> Add release notes for 6_1_2 Critical update

- updates/changelogs/release/6_2_0.md
- updates/v1/entrypoint_release.json
> Add release notes for 6_2_0 Major update

- updates/changelogs/release/6_2_1.md
- updates/v1/entrypoint_release.json
> Add release notes for 6_2_1 Normal update

- updates/changelogs/release/6_2_2.md
- updates/v1/entrypoint_release.json
> Add release notes for 6_2_2 Normal release

- updates/changelogs/release/6_3_0.md
- updates/v1/entrypoint_release.json
> Add release notes for 6_3_0 Major release

- updates/changelogs/release/6_4_0.md
- updates/v1/entrypoint_release.json
> Add release notes for 6_4_0 Major release

- updates/changelogs/release/6_4_1.md
- updates/v1/entrypoint_release.json
> feat: add release notes for 6_4_1 Normal release

- updates/changelogs/release/6_5_0.md
- updates/v1/entrypoint_release.json
> add release notes for 6_5_0 Major release

- updates/changelogs/release/6_5_3.md
- updates/v1/entrypoint_release.json
> feat: add release notes for 6_5_3 Critical release

- updates/changelogs/release/6_7_0.md
- updates/v1/entrypoint_release.json
> Add release notes for 6_7_0 Major release

- updates/changelogs/release/6_7_2.md
- updates/v1/entrypoint_release.json
> Add release notes for 6.7.2 Critical update

- updates/changelogs/release/6_7_3.md
- updates/v1/entrypoint_release.json
> add release notes for 6.7.3 Major update

- updates/changelogs/release/7_0_0.md
- updates/v1/entrypoint_release.json
> add release notes for 7.0.0 Major update

- updates/changelogs/release/7_0_1.md
- updates/v1/entrypoint_release.json
> add release notes for 7.0.1 Normal update

- updates/changelogs/release/7_1_0.md
- updates/v1/entrypoint_release.json
> add release notes for 7.1.0 Major update

- updates/changelogs/release/7_2_0.md
- updates/v1/entrypoint_release.json
> add release notes for 7.2.0 Normal update

- updates/changelogs/release/7_3_0.md
- updates/v1/entrypoint_release.json
> add release notes for 7.3.0 Major update

- updates/changelogs/release/7_3_1.md
- updates/v1/entrypoint_release.json
> add release notes for 7.3.1 Major update

- updates/changelogs/release/7_4_1.md
- updates/changelogs/release/7_4_2.md
- updates/v1/entrypoint_release.json
* add release notes for 7.4.1 Major swap update
* add release notes for 7.4.2 Normal hot fix update
> add release notes for 7.4.1 Major and 7.4.2 Normal update

- updates/changelogs/release/7_5_0.md
- updates/v1/entrypoint_release.json
> add release notes to 7.5.0 Major update

- updates/changelogs/release/7_6_0.md
- updates/v1/entrypoint_release.json
> add release notes to 7.6.0 Major update

- updates/changelogs/release/7_6_1.md
- updates/v1/entrypoint_release.json
> add release notes to 7.6.1 Major update

- updates/changelogs/release/7_7_0.md
- updates/v1/entrypoint_release.json
> add release notes to 7.7.0 Major update

- updates/changelogs/release/8_7_2.md
> Update 8_7_2.md fix
